* ============================================================================
* COINTEGRATION ANALYSIS: GDP-GDI
* ============================================================================
*
* Script: 2_2_gdp_gdi.do
* Purpose: Cointegration analysis: GDP-GDI
* Session: Session 2 • Part 2
* Author: Jesus Villota Miranda
* Date: 2025
*
* This script replicates exercises from the corresponding notebook:
* 2_2_gdp_gdi.ipynb
*
* ============================================================================

* ----------------------------------------------------------------------------
* SETUP
* ----------------------------------------------------------------------------

clear all  // Clear memory and remove all variables
set more off  // Display all output without pausing

* Define paths (relative to dofiles/session2 directory)
global raw_data "../../data/raw"  // Path to raw data
global processed_data "../../data/processed"  // Path to processed data

* Create log file
log using "2_2_gdp_gdi.log", replace text  // Start log file

display "============================================================================"
display "COINTEGRATION ANALYSIS: GDP-GDI"
display "============================================================================"
display ""

* ----------------------------------------------------------------------------
* SECTION 1: INTRODUCTION TO COINTEGRATION
* ----------------------------------------------------------------------------

display "Section 1: Introduction to Cointegration"
display ""

* Cointegration is a fundamental concept in time series econometrics that 
* describes the long-run equilibrium relationship between two or more 
* non-stationary variables. When variables are cointegrated, they share a 
* common stochastic trend and cannot drift arbitrarily far apart over time.
*
* Formal Definition:
*
* Two time series X_t and Y_t are cointegrated of order (d, b), denoted 
* X_t, Y_t ~ CI(d,b), if:
*
* 1. Both series are integrated of order d: X_t ~ I(d) and Y_t ~ I(d)
* 2. There exists a linear combination that is integrated of order d-b where b > 0:
*    Z_t = Y_t - β X_t ~ I(d-b)
*
* The most common case is CI(1,1) where both series are I(1) but their 
* linear combination is I(0) (stationary).
*
* Mathematical Representation:
*
* If X_t and Y_t are both I(1) processes (unit root processes), they can be written as:
*
*     X_t = X_{t-1} + ε_{1t}
*     Y_t = Y_{t-1} + ε_{2t}
*
* If cointegrated with cointegrating vector (1, -β), then:
*
*     Z_t = Y_t - β X_t ~ I(0)
*
* The parameter β is called the cointegrating coefficient, and Z_t is the 
* error correction term or cointegrating residual.
*
* The GDP-GDI Relationship:
*
* GDP (Gross Domestic Product) and GDI (Gross Domestic Income) represent two 
* sides of the same national accounting identity. In theory, they should be equal:
*
*     GDP = GDI
*
* Why?
* - GDP: Measures total value of goods and services produced (production approach)
* - GDI: Measures total income generated by production (income approach)
* - By definition, every dollar of production generates a dollar of income
*
* In Practice:
* - Measurement errors create statistical discrepancy: GDP ≠ GDI
* - Both series trend upward over time (non-stationary, I(1))
* - If cointegrated with β ≈ 1, this confirms the theoretical identity
* - Deviations from equilibrium (Z_t = GDI_t - β · GDP_t) should be temporary

* ----------------------------------------------------------------------------
* 1.1 The Spurious Regression Problem
* ----------------------------------------------------------------------------

display "Subsection 1.1: The Spurious Regression Problem"
display ""

* The Spurious Regression Problem: One of the most important discoveries in 
* econometrics (Granger & Newbold, 1974) is that regressing one non-stationary 
* series on another can produce highly misleading results even when the 
* variables are completely independent.
*
* If we regress one I(1) series on another I(1) series using OLS:
*
*     Y_t = α + β X_t + u_t
*
* Without cointegration:
* - Standard errors are invalid → t-statistics are misleading
* - R² tends to be artificially high
* - Residuals u_t are non-stationary → violates OLS assumptions
* - We find "significant" relationships that are purely spurious
*
* Solution: Test for cointegration first! If cointegrated, use VECM instead 
* of standard regression.
*
* To visualize this, we construct two independent random walks with no causal 
* relationship whatsoever:
*
*     x_t = x_{t-1} + ε_t,    x_0 = 0
*     y_t = y_{t-1} + ν_t,    y_0 = 0
*
* where ε_t, ν_t ~ i.i.d. N(0,1) are independent standard normal shocks.
*
* Key Properties of Random Walks:
* 1. Non-stationary: E[x_t] = 0 but Var(x_t) = tσ² → ∞ as t → ∞
* 2. No mean reversion: Shocks have permanent effects
* 3. Trending behavior: Series wander away from their starting values
*
* The Spurious Regression:
*
* Despite being generated independently, when we estimate:
*
*     y_t = α + β x_t + u_t
*
* we typically observe:
* - Inflated R²
* - Significant t-statistics (often |t| > 2) suggesting "significant" relationship
* - Low Durbin-Watson statistic (DW ≈ 0) indicating strongly serially correlated residuals
*
* Why This Happens: Both series drift randomly over time. By chance, they may 
* drift in similar directions during certain periods, creating the illusion of 
* a relationship. The residuals û_t inherit the non-stationarity of x_t and y_t, 
* violating the basic assumption that errors are stationary with constant variance.

* ----------------------------------------------------------------------------
* Spurious Regression Demonstration: Two Independent Random Walks
* ----------------------------------------------------------------------------

clear all
set obs 250                    // Sample size (250 observations)
set seed 12345                 // Seed that produces more typical spurious result

* Generate time index and declare as time series
gen t = _n
tsset t                        // Declare time series structure

* Generate independent random shocks: ε_t, ν_t ~ N(0,1)
gen eps = rnormal()
gen nu = rnormal()

* Construct random walks: x_t = x_{t-1} + ε_t, y_t = y_{t-1} + ν_t
gen x_rw = sum(eps)            // Cumulative sum creates random walk
gen y_rw = sum(nu)             // Completely independent of x_rw

* Display summary statistics for the random walks
display _newline "{txt}{hline 60}"
display "{txt}Summary Statistics for Independent Random Walks"
display "{txt}{hline 60}"
summarize x_rw y_rw

* Correlation between contemporaneous values (spurious!)
display _newline "{txt}Correlation between independent random walks:"
correlate x_rw y_rw

* Run the spurious regression: y_t = α + β·x_t + u_t
display _newline "{txt}{hline 60}"
display "{txt}Spurious Regression: y_t = α + β·x_t + u_t"
display "{txt}{hline 60}"
quietly regress y_rw x_rw

* Calculate Durbin-Watson statistic explicitly
quietly estat dwatson
local dw = r(dw)

* Extract key statistics
local beta = _b[x_rw]
local se_beta = _se[x_rw]
local t_stat = `beta'/`se_beta'
local r2 = e(r2)
local N = e(N)

* Display full regression output
regress y_rw x_rw

* Display interpretation
display _newline "{txt}{hline 60}"
display "{txt}Spurious Regression Results Summary:"
display "{txt}{hline 60}"
display "{txt}Coefficient (β):     {res}" %7.4f `beta' "{txt}  (should be ~0 if no relation)"
display "{txt}Standard Error:      {res}" %7.4f `se_beta'
display "{txt}t-statistic:         {res}" %7.3f `t_stat' "{txt}  (appears 'significant'!)"
display "{txt}R-squared:           {res}" %7.4f `r2' "{txt}  (" %4.1f `r2'*100 "% of variation 'explained')"
display "{txt}Durbin-Watson:       {res}" %7.4f `dw' "{txt}  (DW≈0 indicates strong serial correlation)"
display "{txt}{hline 60}"
display "{err}⚠  WARNING: Despite statistical significance,"
display "{err}   these series are INDEPENDENT by construction!"
display "{err}   This demonstrates the SPURIOUS REGRESSION problem."
display "{txt}{hline 60}" _newline

* Generate predictions and residuals for visualization
predict yhat, xb
predict resid, resid

* VISUALIZATION 1: Time series plots of both random walks
twoway (line x_rw t, lcolor(navy) lwidth(medium)) ///
       (line y_rw t, lcolor(maroon) lwidth(medium)), ///
    title("Two Independent Random Walks", size(medium) color(black)) ///
    subtitle("Both series drift randomly with no causal link", size(small)) ///
    ytitle("Value", size(small)) xtitle("Time", size(small)) ///
    legend(order(1 "x{subscript:t} (random walk 1)" 2 "y{subscript:t} (random walk 2)") ///
           size(small) position(6) rows(1)) ///
    name(sr_timeseries, replace)

* VISUALIZATION 2: Scatter plot with spurious regression line
twoway (scatter y_rw x_rw, msymbol(circle) msize(small) mcolor(navy%40)) ///
       (lfit y_rw x_rw, lcolor(red) lwidth(medthick)), ///
    title("Spurious Regression: y{subscript:t} vs x{subscript:t}", size(medium) color(black)) ///
    subtitle("R² = `: display %4.3f `r2'' with t = `: display %4.2f `t_stat'' despite independence", size(small)) ///
    ytitle("y{subscript:t} (random walk 2)", size(small)) ///
    xtitle("x{subscript:t} (random walk 1)", size(small)) ///
    legend(order(1 "Observed pairs" 2 "OLS fit: β = `: display %5.3f `beta''") ///
           size(small) position(6) rows(1)) ///
    note("False relationship due to both series being non-stationary", size(vsmall)) ///
    name(sr_scatter, replace)

* VISUALIZATION 3: Residual plot showing non-stationary behavior
twoway (line resid t, lcolor(red) lwidth(medium)) ///
       (line yhat t, lcolor(blue%30) lwidth(thin) lpattern(dash)), ///
    title("Non-Stationary Residuals from Spurious Regression", size(medium) color(black)) ///
    subtitle("Residuals drift and exhibit strong persistence (DW = `: display %4.3f `dw'')", size(small)) ///
    ytitle("Value", size(small)) xtitle("Time", size(small)) ///
    yline(0, lcolor(gs10) lpattern(solid)) ///
    legend(order(1 "Residuals (û{subscript:t})" 2 "Fitted values (ŷ{subscript:t})") ///
           size(small) position(6) rows(1)) ///
    name(sr_resid, replace)

* VISUALIZATION 4: ACF of residuals (should show strong persistence)
ac resid, lags(40) ///
    title("ACF of Residuals: Evidence of Non-Stationarity", size(medium)) ///
    subtitle("Slow decay indicates residuals inherit the unit root", size(small)) ///
    name(sr_acf_resid, replace)

* ----------------------------------------------------------------------------
* 1.3 Why Cointegration Matters
* ----------------------------------------------------------------------------

display _newline(2) "Subsection 1.3: Why Cointegration Matters"
display ""

* Cointegration has profound implications for economic modeling and policy:
*
* 1. Long-run Equilibrium: Identifies stable relationships between variables
* 2. Error Correction: Shows how variables adjust to restore equilibrium
* 3. Forecasting: Improves long-horizon predictions by incorporating equilibrium constraint
* 4. Policy Analysis: Reveals which variables adjust when disequilibrium occurs
* 5. Economic Theory: Tests theoretical relationships (like GDP = GDI)
*
* Key Distinction:
*
* Concept              Description              Example
* Correlation          Short-run co-movement    Two stocks move together daily
* Cointegration        Long-run equilibrium     GDP and GDI cannot diverge permanently

* ----------------------------------------------------------------------------
* SECTION 2: DATA LOADING AND INITIAL EXPLORATION
* ----------------------------------------------------------------------------

display _newline(2) "Section 2: Data Loading and Initial Exploration"
display ""

* ----------------------------------------------------------------------------
* 2.1 Loading the Data
* ----------------------------------------------------------------------------

display "Subsection 2.1: Loading the Data"
display ""

* We'll work with two US macroeconomic series:
* - US_GDP.csv: US Gross Domestic Product (quarterly, 1947-2025)
* - US_GDI.csv: Gross Domestic Income (quarterly, 1947-2025)
*
* Both series are measured in billions of dollars and were obtained from FRED.

* Clear environment and set up paths
clear all
set more off

* Define data paths
global raw_data "../../data/raw"
global processed_data "../../data/processed"

* Load GDP data
import delimited "$raw_data/US_GDP.csv", clear varnames(1)

* Rename and format date
rename observation_date date_str
* Convert date string (YYYY-MM-DD) to daily date, then to quarterly
gen date_daily = daily(date_str, "YMD")
gen date = qofd(date_daily)
format date %tq
drop date_daily
* Keep only necessary variables
keep date gdp

* Take natural log of GDP
gen gdp_ln = ln(gdp)
drop gdp
rename gdp_ln gdp

* Save as temporary file
tempfile gdp_data
save `gdp_data'

* Load GDI data
import delimited "$raw_data/US_GDI.csv", clear varnames(1)
rename observation_date date_str
* Convert date string (YYYY-MM-DD) to daily date, then to quarterly
gen date_daily = daily(date_str, "YMD")
gen date = qofd(date_daily)
format date %tq
drop date_daily
* GDI column already named correctly
keep date gdi

* Take natural log of GDI
gen gdi_ln = ln(gdi)
drop gdi
rename gdi_ln gdi

* Check for duplicates before merging
duplicates report date
duplicates list date

* Merge with GDP data
merge 1:1 date using `gdp_data'

* Keep only observations where both series exist
keep if _merge == 3
drop _merge

* Declare as time series
tsset date

* Display first and last observations
display _newline "First 5 observations:"
list date gdp gdi in 1/5
display _newline "Last 5 observations:"
list date gdp gdi in -5/-1

* ----------------------------------------------------------------------------
* 2.2 Summary Statistics
* ----------------------------------------------------------------------------

display _newline(2) "Subsection 2.2: Summary Statistics"
display ""

* Display dataset structure and summary
describe
summarize gdp gdi, detail

* ----------------------------------------------------------------------------
* 2.3 Time Series Visualization
* ----------------------------------------------------------------------------

display _newline(2) "Subsection 2.3: Time Series Visualization"
display ""

* Both GDP and GDI exhibit clear upward trends, characteristic of I(1) processes.
* Let's visualize their evolution over time to identify:
* - Long-run trending behavior
* - Potential structural breaks
* - Co-movement patterns
*
* What to Look For:
* - Non-stationarity: Both series should show persistent upward trends
* - Parallel trends: If cointegrated, series should move together despite short-run deviations
* - Similar growth rates: GDP and GDI should exhibit comparable long-run growth patterns

* Plot GDP & GDI in levels for comparison
tsline gdp gdi, ///
    title("GDP and GDI - Comparative Evolution", size(medium)) ///
    ytitle("Value") ///
    xtitle("Quarter") ///
    tlabel(, format(%tqCY)) ///
    legend(label(1 "GDP") label(2 "GDI") position(6) rows(1)) ///
    note("Both series exhibit clear upward trends") ///
    scheme(s2color)
* graph export "../../notebooks/figures/gdp_gdi_comparison.png", replace width(1200)

* Plot GDP and GDI growth rates for comparison
gen gdp_growth = 100 * (gdp - L.gdp) / L.gdp
gen gdi_growth = 100 * (gdi - L.gdi) / L.gdi

tsline gdp_growth gdi_growth, ///
    title("GDP and GDI - Quarterly Growth Rates", size(medium)) ///
    ytitle("Growth Rate (%)") ///
    xtitle("Quarter") ///
    tlabel(, format(%tqCY)) ///
    legend(label(1 "GDP Growth") label(2 "GDI Growth") position(6) rows(1)) ///
    note("Quarterly percentage change of both series") ///
    scheme(s2color)
* graph export "../../notebooks/figures/gdp_gdi_growth_comparison.png", replace width(1200)

* ----------------------------------------------------------------------------
* 2.4 Scatter Plot and Linear Relationship
* ----------------------------------------------------------------------------

display _newline(2) "Subsection 2.4: Scatter Plot and Linear Relationship"
display ""

* A scatter plot of GDP vs GDI reveals whether a linear long-run relationship 
* exists between the two variables. If cointegrated, we expect to see:
* - Strong positive linear pattern
* - Points clustering around a stable line
* - Minimal deviation from the trend
*
* This visual check complements formal cointegration tests.

* Scatter plot: GDP vs GDI
twoway (scatter gdi gdp, mcolor(navy%40) msize(small)) ///
       (lfit gdi gdp, lcolor(red) lwidth(medium)), ///
    title("GDP vs GDI - Linear Relationship", size(medium)) ///
    xtitle("GDP (log)") ///
    ytitle("GDI (log)") ///
    legend(label(1 "Data points") label(2 "Linear fit") position(6) rows(1)) ///
    note("Strong linear relationship suggests potential cointegration") ///
    scheme(s2color)
* graph export "../../notebooks/figures/gdp_gdi_scatter.png", replace width(1200)

* Simple correlation analysis
display _newline "Correlation Analysis:"
correlate gdp gdi
display "Correlation coefficient: " %6.4f r(rho)

* ----------------------------------------------------------------------------
* SECTION 3: UNIT ROOT TESTING: ARE BOTH SERIES I(1)?
* ----------------------------------------------------------------------------

display _newline(2) "Section 3: Unit Root Testing: Are Both Series I(1)?"
display ""

* Before testing for cointegration, we must verify that both series are 
* integrated of the same order. The Johansen cointegration test requires 
* both variables to be I(1) processes.
*
* Why Unit Root Tests Matter:
*
* For cointegration to exist between X_t and Y_t:
* 1. Both must be non-stationary (typically I(1))
* 2. A linear combination must be stationary (I(0))
*
* If both series are already I(0), standard VAR modeling is appropriate—no 
* need for VECM.
*
* Key Concept: An I(1) process becomes stationary after first-differencing: 
* if X_t ~ I(1), then ΔX_t ~ I(0).

* ----------------------------------------------------------------------------
* 3.1 Testing GDP for Unit Root
* ----------------------------------------------------------------------------

display _newline(2) "Subsection 3.1: Testing GDP for Unit Root"
display ""

* We'll use the DF-GLS test (Elliott, Rothenberg, and Stock, 1996), which has 
* better power than the standard ADF test, especially for small samples. 
* The test regression is:
*
*     Δy_t^d = α y_{t-1}^d + Σ_{i=1}^{p} β_i Δy_{t-i}^d + ε_t
*
* where y_t^d is the detrended series.
*
* Hypotheses:
* - H_0: α = 0 (unit root exists, series is non-stationary)
* - H_1: α < 0 (no unit root, series is stationary)
*
* Decision Rule: If test statistic < critical value → reject H_0 → stationary

* DF-GLS unit root test for GDP (levels)
* Test with different lag lengths to check robustness
display _newline(2) "======================================================================"
display "DF-GLS Unit Root Test: GDP (Levels)"
display "======================================================================"

* Lag 1
dfgls gdp, maxlag(1) notrend
display _newline(1) "Lag 1: Test statistic = " %8.4f r(Zt_gls)

* Lag 2
dfgls gdp, maxlag(2) notrend
display _newline(1) "Lag 2: Test statistic = " %8.4f r(Zt_gls)

* Lag 3
dfgls gdp, maxlag(3) notrend
display _newline(1) "Lag 3: Test statistic = " %8.4f r(Zt_gls)

display _newline(1) "Critical Values (MacKinnon):"
display "  1%: -2.58    5%: -1.94    10%: -1.62"
display _newline(1) "Interpretation: Fail to reject H0 → GDP has unit root (I(1))"
display "======================================================================"

* ----------------------------------------------------------------------------
* 3.2 Testing GDI for Unit Root
* ----------------------------------------------------------------------------

display _newline(2) "Subsection 3.2: Testing GDI for Unit Root"
display ""

* We apply the same DF-GLS procedure to GDI. If both GDP and GDI fail to 
* reject the unit root null hypothesis, we can proceed with cointegration testing.

* DF-GLS unit root test for GDI (levels)
display _newline(2) "======================================================================"
display "DF-GLS Unit Root Test: GDI (Levels)"
display "======================================================================"

* Lag 1
dfgls gdi, maxlag(1) notrend
display _newline(1) "Lag 1: Test statistic = " %8.4f r(Zt_gls)

* Lag 2
dfgls gdi, maxlag(2) notrend
display _newline(1) "Lag 2: Test statistic = " %8.4f r(Zt_gls)

* Lag 3
dfgls gdi, maxlag(3) notrend
display _newline(1) "Lag 3: Test statistic = " %8.4f r(Zt_gls)

display _newline(1) "Critical Values (MacKinnon):"
display "  1%: -2.58    5%: -1.94    10%: -1.62"
display _newline(1) "Interpretation: Fail to reject H0 → GDI has unit root (I(1))"
display "======================================================================"

* ----------------------------------------------------------------------------
* 3.3 ACF/PACF Analysis
* ----------------------------------------------------------------------------

display _newline(2) "Subsection 3.3: ACF/PACF Analysis"
display ""

* The autocorrelation function (ACF) and partial autocorrelation function (PACF) 
* provide visual evidence of non-stationarity:
* - I(1) processes: ACF decays very slowly, remains high for many lags
* - I(0) processes: ACF decays quickly to zero
*
* High persistence in ACF confirms unit root test results.

ac gdp, lags(20) ///
    name(ac_gdp, replace) ///
    title("GDP - Autocorrelation Function", size(medium)) ///
    scheme(s2color)

pac gdp, lags(20) ///
    name(pac_gdp, replace) ///
    title("GDP - Partial Autocorrelation Function", size(medium)) ///
    scheme(s2color)

ac gdi, lags(20) ///
    name(ac_gdi, replace) ///
    title("GDI - Autocorrelation Function", size(medium)) ///
    scheme(s2color)

pac gdi, lags(20) ///
    name(pac_gdi, replace) ///
    title("GDI - Partial Autocorrelation Function", size(medium)) ///
    scheme(s2color)

graph combine ac_gdp pac_gdp ac_gdi pac_gdi, ///
    cols(2) ///
    title("ACF and PACF for GDP and GDI") ///
    ycommon xcommon scheme(s2color)

* ----------------------------------------------------------------------------
* Interpretation Summary
* ----------------------------------------------------------------------------

display _newline(2) "======================================================================"
display "Interpretation Summary"
display "======================================================================"
display ""
display "Based on the DF-GLS tests and ACF/PACF analysis:"
display ""
display "✓ GDP: Exhibits unit root (I(1)) - test statistics fail to reject null hypothesis"
display "✓ GDI: Exhibits unit root (I(1)) - test statistics fail to reject null hypothesis"
display "✓ ACF patterns: Both series show high persistence characteristic of I(1) processes"
display ""
display "Conclusion: Both series are integrated of the same order →"
display "            prerequisite for cointegration testing is satisfied"
display ""
display "We can now proceed to test whether these two I(1) series are cointegrated."
display "======================================================================"

* ----------------------------------------------------------------------------
* SECTION 4: TESTING FOR COINTEGRATION: JOHANSEN TEST
* ----------------------------------------------------------------------------

display _newline(2) "Section 4: Testing for Cointegration: Johansen Test"
display ""

* The Johansen test (Johansen, 1988, 1991) is the most widely used multivariate 
* cointegration test. It determines:
* 1. Number of cointegrating relationships (rank of cointegration matrix)
* 2. Cointegrating vectors that define long-run equilibrium
*
* Johansen Test Framework:
*
* The test is based on a VAR(p) model that can be written in error correction form:
*
*     ΔY_t = Π Y_{t-1} + Σ_{i=1}^{p-1} Γ_i ΔY_{t-i} + ε_t
*
* where:
* - Y_t := [GDP_t, GDI_t]' is a 2×1 vector
* - Π = α β' is the long-run impact matrix (2×2)
* - rank(Π) determines the number of cointegrating relationships
* - β contains the cointegrating vectors
* - α contains the adjustment coefficients (loading matrix)
*
* Key Insight: rank(Π) = 0 → no cointegration; rank(Π) = 1 → one cointegrating relationship
*
* Two Test Statistics:
*
* 1. Trace Test: Tests H_0: rank ≤ r vs H_1: rank = 2
*        Trace = -T Σ_{i=r+1}^{2} ln(1 - λ̂_i)
*
* 2. Maximum Eigenvalue Test: Tests H_0: rank = r vs H_1: rank = r+1
*        Max-Eigen = -T ln(1 - λ̂_{r+1})
*
* where λ̂_i are estimated eigenvalues (ordered: λ̂_1 > λ̂_2).

* ----------------------------------------------------------------------------
* 4.1 Lag Selection for VAR
* ----------------------------------------------------------------------------

display _newline(2) "Subsection 4.1: Lag Selection for VAR"
display ""

* Before running Johansen test, we must select appropriate lag length for the 
* underlying VAR model using information criteria.

* Determine optimal lag length for VAR using information criteria
varsoc gdp gdi, maxlag(20)

display _newline(2) "Based on AIC and BIC, we select lag order for subsequent analysis"

* ----------------------------------------------------------------------------
* 4.2 Johansen Cointegration Test
* ----------------------------------------------------------------------------

display _newline(2) "Subsection 4.2: Johansen Cointegration Test"
display ""

* Interpreting Test Results:
*
* The Johansen test produces two test statistics for each rank hypothesis:
*
* Trace Test Interpretation:
* - Tests H_0: rank ≤ r against H_1: rank = k (full rank)
* - Start with r = 0: If trace statistic > critical value → reject H_0 → 
*   at least one cointegrating relationship
* - Continue testing r = 1, 2, ... until we fail to reject
*
* Maximum Eigenvalue Test Interpretation:
* - Tests H_0: rank = r against H_1: rank = r+1
* - More powerful for testing specific rank values
* - If max-eigen statistic > critical value → reject H_0 → rank is at least r+1
*
* Decision Rule:
* 1. Start with rank = 0: If both tests reject → evidence of cointegration
* 2. Check rank = 1: If both tests fail to reject → exactly one cointegrating relationship
* 3. For our 2-variable system: Maximum rank = 1 (if both variables are I(1))
*
* Typical Output:
* - Trace test for rank = 0: Large statistic → reject → cointegration exists
* - Trace test for rank ≤ 1: Small statistic → fail to reject → rank = 1
* - Max-eigen test confirms: rank = 1

* Johansen cointegration test
* Using lag=3 based on information criteria
display _newline(2) "======================================================================"
display "JOHANSEN COINTEGRATION TEST: GDP and GDI"
display "======================================================================"

vecrank gdp gdi, lags(3) trend(trend) max

display _newline(2) "Interpretation:"
display "  • Trace test: Tests H0: rank ≤ r"
display "  • Max-Eigen test: Tests H0: rank = r"
display "  • If test statistic > 5% critical value → reject H0"
display "======================================================================"

* After running the Johansen test, examine the output:
*
* 1. Trace test statistics: Compare to 5% critical values
*    - If trace(0) > critical value → reject H_0: rank = 0 → cointegration exists
*    - If trace(1) < critical value → fail to reject H_0: rank ≤ 1 → rank = 1
*
* 2. Max-eigen test statistics: Confirm rank determination
*    - If max-eigen(0) > critical value → at least one cointegrating relationship
*    - If max-eigen(1) < critical value → exactly one relationship
*
* 3. Cointegrating vector: Shows the long-run relationship
*    - For GDP-GDI, expect β_1 ≈ 1 (one-to-one relationship)
*
* Conclusion: If both tests indicate rank = 1, proceed to estimate VECM with 
* one cointegrating relationship.

* ----------------------------------------------------------------------------
* SECTION 5: THE COINTEGRATING RELATIONSHIP
* ----------------------------------------------------------------------------

display _newline(2) "Section 5: The Cointegrating Relationship"
display ""

* ----------------------------------------------------------------------------
* 5.1 Estimating the Cointegrating Vector
* ----------------------------------------------------------------------------

display _newline(2) "Subsection 5.1: Estimating the Cointegrating Vector"
display ""

* If the Johansen test confirms cointegration (rank = 1), we can estimate the 
* cointegrating vector β that defines the long-run equilibrium relationship:
*
*     GDI_t = β_0 + β_1 · GDP_t + Z_t
*
* where Z_t is the error correction term (cointegrating residual). In equilibrium, 
* Z_t = 0; deviations represent temporary disequilibria that should correct over time.
*
* Economic Interpretation:
*
* For GDP and GDI:
* - Theory predicts: β_1 ≈ 1 (one-to-one long-run relationship)
* - If β_1 = 1: Every dollar of GDP generates one dollar of income
* - If Z_t > 0: GDI above equilibrium → expect downward adjustment
* - If Z_t < 0: GDI below equilibrium → expect upward adjustment
*
* The VECM reveals which variable adjusts to restore equilibrium.

* Estimate VECM to extract cointegrating vector
* Using rank(1) based on Johansen test results
vec gdp gdi, lags(3) rank(1)

* The cointegrating vector is displayed in the output above
* Beta coefficients show the long-run relationship
*
* Interpretation of results:
*
* Cointegrating equation:
*     [1, -1.000953]' [ln GDP, ln GDI]' + 0.0479096 = 0
*
* Or equivalently,
*     ln GDP = 1.000953 · ln GDI - 0.0479096
*
* Interpretation of coefficients:
* - β_1 (gdp): 1.0 (normalized for identification)
* - β_2 (gdi): -1.000953 (statistically significant, p < 0.001)
* - Constant: -0.0479096
*
* Economic meaning:
* - The long-run relationship between GDP and GDI is approximately one-to-one 
*   (1.000953 ≈ 1.0), as economic theory predicts: GDP ≈ GDI.
* - The intercept term is close to 0, which suggests that there is no evidence 
*   of a persistent measurement gap between GDP and GDI in the long run.

* ----------------------------------------------------------------------------
* 5.2 The Error Correction Term
* ----------------------------------------------------------------------------

display _newline(2) "Subsection 5.2: The Error Correction Term"
display ""

* The error correction term (ECT) represents deviations from long-run equilibrium. 
* Let's construct and visualize it:
*
*     ECT_t = Z_t = GDI_t - β̂_0 - β̂_1 · GDP_t
*
* A stationary ECT confirms cointegration—the deviations are mean-reverting.

* Predict the error correction term (cointegrating residual)
predict ce_term, ce

* Plot the error correction term
tsline ce_term, ///
    title("Error Correction Term (Cointegrating Residual)", size(medium)) ///
    ytitle("Deviation from Equilibrium") ///
    xtitle("Quarter") ///
    yline(0, lcolor(red) lpattern(dash)) ///
    tlabel(, format(%tqCY)) ///
    note("Mean-reverting pattern indicates cointegration") ///
    scheme(s2color)
* graph export "../../notebooks/figures/error_correction_term.png", replace width(1200)

* Test stationarity of the error correction term
* If ECT is stationary (I(0)), this confirms cointegration
display _newline(2) "Testing Stationarity of Error Correction Term:"
dfgls ce_term, maxlag(2) trend

display _newline(1) "If test statistic < -1.94 (5% critical value), ECT is stationary"
display "Stationary ECT confirms the cointegrating relationship"

* ACF of error correction term (should decay quickly if stationary)
ac ce_term, lags(20) ///
    title("Error Correction Term - Autocorrelation Function", size(medium)) ///
    note("Quick decay confirms stationarity") ///
    scheme(s2color)
* graph export "../../notebooks/figures/ect_acf.png", replace width(1200)

* ----------------------------------------------------------------------------
* END OF SCRIPT
* ----------------------------------------------------------------------------

display _newline(2) "============================================================================"
display "END OF COINTEGRATION ANALYSIS"
display "============================================================================"

* Close log file
log close
